services:
  portafolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"    # Mapea el puerto 80 del contenedor al puerto 80 del host
      - "443:443"  # Si estás usando HTTPS, mapea el puerto 443
    restart: always  # Asegura que el contenedor se reinicie si falla